//! The standard-library snapshots: which top-level names are `stdlib` for a Python version.
//!
//! - Decision: [ADR-0013](../../../docs/adr/0013-ruff-parser-for-python.md) (a bundled
//!   `sys.stdlib_module_names` per supported interpreter version, committed)
//! - Plan: [Wave 2, Step 4](../../../docs/plans/pending/0002-wave-2-dotnet-python-element-rules.md#24-step-4-the-python-extractor-2b)
//!   (`stdlib/`), resolution step three of
//!   [§ 1.4.4](../../../docs/plans/pending/0002-wave-2-dotnet-python-element-rules.md#144-python-resolution-order)
//! - Requirement: [FR-EXT-PY-01](../../../docs/prd.md#fr-ext-py-01)
//!
//! Each `stdlib/3.X.txt` is generated by `tools/gen-stdlib.py`, whose docstring says how each
//! version's list was produced (3.10 to 3.14 from their own interpreters, 3.8 and 3.9 derived
//! from 3.10 by the documented removals and additions). The files are data, embedded with
//! `include_str!`, so nothing here runs an interpreter.

use std::collections::BTreeSet;

/// The supported versions and their snapshots, oldest first.
const SNAPSHOTS: &[(&str, &str)] = &[
    ("3.8", include_str!("stdlib/3.8.txt")),
    ("3.9", include_str!("stdlib/3.9.txt")),
    ("3.10", include_str!("stdlib/3.10.txt")),
    ("3.11", include_str!("stdlib/3.11.txt")),
    ("3.12", include_str!("stdlib/3.12.txt")),
    ("3.13", include_str!("stdlib/3.13.txt")),
    ("3.14", include_str!("stdlib/3.14.txt")),
];

/// The default version when neither the configuration nor `requires-python` names one.
pub const DEFAULT_VERSION: &str = "3.13";

/// The versions with a bundled snapshot, oldest first.
pub fn supported() -> Vec<&'static str> {
    SNAPSHOTS.iter().map(|(v, _)| *v).collect()
}

/// `major.minor` of a version string (`3.12.1` is `3.12`), or `None` when it is not one.
pub fn major_minor(version: &str) -> Option<String> {
    let mut parts = version.trim().split('.');
    let major: u32 = parts.next()?.parse().ok()?;
    let minor: u32 = parts.next()?.parse().ok()?;
    Some(format!("{major}.{minor}"))
}

/// One version's standard-library top-level names.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StdlibSet {
    version: &'static str,
    names: BTreeSet<&'static str>,
}

impl StdlibSet {
    /// The snapshot for `version` (`3.12` or `3.12.4`), or `None` when none is bundled.
    pub fn for_version(version: &str) -> Option<Self> {
        let wanted = major_minor(version)?;
        SNAPSHOTS
            .iter()
            .find(|(v, _)| *v == wanted)
            .map(|(version, text)| Self {
                version,
                names: text.lines().filter(|l| !l.is_empty()).collect(),
            })
    }

    /// The `major.minor` version the snapshot is for.
    pub fn version(&self) -> &'static str {
        self.version
    }

    /// Whether a dotted module name belongs to the standard library, judged by its top-level
    /// name as `sys.stdlib_module_names` is (`os.path` is stdlib because `os` is).
    pub fn contains(&self, dotted: &str) -> bool {
        let top = dotted.split('.').next().unwrap_or_default();
        self.names.contains(top)
    }

    /// How many top-level names the snapshot lists.
    pub fn len(&self) -> usize {
        self.names.len()
    }

    /// Whether the snapshot is empty (never, for a bundled one).
    pub fn is_empty(&self) -> bool {
        self.names.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The resolver table of plan § 2.4: modules that moved between versions.
    #[test]
    fn modules_that_moved_between_versions() {
        let table: &[(&str, &str, bool)] = &[
            ("distutils", "3.8", true),
            ("distutils", "3.11", true),
            ("distutils", "3.12", false),
            ("distutils.core", "3.11", true),
            ("tomllib", "3.10", false),
            ("tomllib", "3.11", true),
            ("tomllib", "3.14", true),
            ("asyncore", "3.11", true),
            ("asyncore", "3.12", false),
            ("asynchat", "3.12", false),
            ("imp", "3.11", true),
            ("imp", "3.12", false),
            ("smtpd", "3.12", false),
            ("imghdr", "3.12", true),
            ("imghdr", "3.13", false),
            ("cgi", "3.12", true),
            ("cgi", "3.13", false),
            ("telnetlib", "3.13", false),
            ("lib2to3", "3.12", true),
            ("lib2to3", "3.13", false),
            ("graphlib", "3.8", false),
            ("graphlib", "3.9", true),
            ("zoneinfo", "3.8", false),
            ("zoneinfo", "3.9", true),
            ("dummy_threading", "3.8", true),
            ("dummy_threading", "3.9", false),
            ("parser", "3.9", true),
            ("parser", "3.10", false),
            ("formatter", "3.9", true),
            ("formatter", "3.10", false),
            ("binhex", "3.10", true),
            ("binhex", "3.11", false),
            ("annotationlib", "3.13", false),
            ("annotationlib", "3.14", true),
            ("compression.zstd", "3.14", true),
            ("os.path", "3.8", true),
            ("json", "3.14", true),
            ("requests", "3.13", false),
        ];
        for &(module, version, expected) in table {
            let set = StdlibSet::for_version(version);
            assert_eq!(
                set.map(|s| s.contains(module)),
                Some(expected),
                "{module} in {version}"
            );
        }
    }

    #[test]
    fn every_supported_version_has_a_sorted_non_empty_snapshot() {
        let versions = supported();
        assert_eq!(
            versions,
            ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        );
        for (version, text) in SNAPSHOTS {
            let lines: Vec<&str> = text.lines().collect();
            let mut sorted = lines.clone();
            sorted.sort_unstable();
            sorted.dedup();
            assert_eq!(lines, sorted, "{version} is sorted and unique");
            let set = StdlibSet::for_version(version);
            assert_eq!(set.as_ref().map(StdlibSet::version), Some(*version));
            assert!(set.as_ref().is_some_and(|s| s.len() > 250 && !s.is_empty()));
        }
        assert!(versions.contains(&DEFAULT_VERSION));
    }

    #[test]
    fn versions_are_read_as_major_minor() {
        assert_eq!(major_minor("3.12.4").as_deref(), Some("3.12"));
        assert_eq!(major_minor(" 3.9 ").as_deref(), Some("3.9"));
        assert_eq!(major_minor("3"), None);
        assert_eq!(major_minor("three.x"), None);
        assert_eq!(
            StdlibSet::for_version("3.12.4").map(|s| s.version()),
            Some("3.12")
        );
        assert!(StdlibSet::for_version("3.7").is_none());
        assert!(StdlibSet::for_version("2.7").is_none());
        assert!(StdlibSet::for_version("").is_none());
    }
}
