#!/usr/bin/env python3
# Copyright (c) 2026 Ben Bahrenburg. MIT License.
"""Regenerate the standard-library snapshots under ``src/stdlib/``.

Plan: docs/plans/pending/0002-wave-2-dotnet-python-element-rules.md, Step 4 (sub-wave 2B).
Decision: docs/adr/0013-ruff-parser-for-python.md (a bundled ``sys.stdlib_module_names`` per
supported interpreter version, regenerated by this script and committed).

Two modes, and each committed file names the mode that wrote it only through this docstring:

``python3.X tools/gen-stdlib.py``
    Writes ``src/stdlib/3.X.txt`` from the running interpreter's ``sys.stdlib_module_names``,
    one name per line, sorted. This is the authoritative source and needs Python 3.10 or newer,
    the first release with that attribute. The 3.10 to 3.14 snapshots were written this way,
    each by its own interpreter; where an interpreter is not installed, ``uv`` provides one
    without touching the system (``uv run --no-project --python 3.13 python tools/gen-stdlib.py``).

``python3 tools/gen-stdlib.py --derive``
    Writes ``src/stdlib/3.8.txt`` and ``src/stdlib/3.9.txt``, which no interpreter can print
    because ``sys.stdlib_module_names`` does not exist before 3.10. Each is the committed
    ``3.10.txt`` with the documented differences applied (``DERIVED`` below):

    - 3.9 has ``formatter``, ``parser`` and ``symbol`` (removed in 3.10, "What's New In
      Python 3.10", Removed), ``_peg_parser`` (the 3.9-only parser module, removed with the old
      parser in 3.10) and ``_bootlocale`` (removed in 3.10, bpo-42208).
    - 3.8 is 3.9 without ``graphlib`` and ``zoneinfo``/``_zoneinfo`` (new in 3.9, "What's New In
      Python 3.9", New Modules), ``_aix_support`` and ``_bootsubprocess`` (new private modules
      in 3.9) and ``_peg_parser``, and with ``dummy_threading`` and ``_dummy_thread`` (removed in
      3.9, bpo-37312).

    The differences were checked by listing the top-level modules of real 3.8.20 and 3.9.6
    installations (``pkgutil.iter_modules`` over the stdlib and ``lib-dynload`` folders plus
    ``sys.builtin_module_names``) against ``3.10.txt``; platform-only modules such as ``nt`` or
    ``msvcrt`` are kept, as ``sys.stdlib_module_names`` keeps them on every platform.

The script never runs at extraction time: the extractor embeds the committed files and executes
no interpreter.
"""

from __future__ import annotations

import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "stdlib"

# version: (base version, names to add, names to remove), applied in order.
DERIVED: dict[str, tuple[str, frozenset[str], frozenset[str]]] = {
    "3.9": (
        "3.10",
        frozenset({"formatter", "parser", "symbol", "_peg_parser", "_bootlocale"}),
        frozenset(),
    ),
    "3.8": (
        "3.9",
        frozenset({"dummy_threading", "_dummy_thread"}),
        frozenset(
            {
                "graphlib",
                "zoneinfo",
                "_zoneinfo",
                "_aix_support",
                "_bootsubprocess",
                "_peg_parser",
            },
        ),
    ),
}


def write(version: str, names: set[str]) -> None:
    """Write one snapshot, sorted, one name per line."""
    path = OUT / f"{version}.txt"
    path.write_text("".join(f"{name}\n" for name in sorted(names)), encoding="utf-8")
    sys.stdout.write(f"wrote {path} ({len(names)} names)\n")


def read(version: str) -> set[str]:
    """Read one committed snapshot."""
    text = (OUT / f"{version}.txt").read_text(encoding="utf-8")
    return {line for line in text.splitlines() if line}


def derive() -> None:
    """Write the snapshots that precede ``sys.stdlib_module_names``."""
    for version, (base, add, remove) in DERIVED.items():
        write(version, (read(base) | add) - remove)


def live() -> None:
    """Write the running interpreter's snapshot."""
    names = getattr(sys, "stdlib_module_names", None)
    if names is None:
        sys.stderr.write("sys.stdlib_module_names needs Python 3.10+; use --derive\n")
        raise SystemExit(2)
    write(f"{sys.version_info.major}.{sys.version_info.minor}", set(names))


if __name__ == "__main__":
    if sys.argv[1:] == ["--derive"]:
        derive()
    else:
        live()
