[project]
name = "app"
version = "0.1.0"

[tool.importlinter]
root_packages = ["app"]

[[tool.importlinter.contracts]]
id = "layered"
name = "Each bounded context is layered"
type = "layers"
containers = ["app.billing", "app.shipping"]
layers = ["web | api", "(infra)", "domain"]
exhaustive = true
exhaustive_ignores = ["tests"]

[[tool.importlinter.contracts]]
name = "Top level"
type = "layers"
layers = ["app.billing : app.shipping", "app.core"]

[[tool.importlinter.contracts]]
name = "A contract of our own"
type = "app.contracts.MyContract"
