[metadata]
name = pkg

[importlinter]
root_package = pkg

[importlinter:contract:features]
name = Features are independent
type = independence
modules =
    pkg.features.cart
    pkg.features.search
    pkg.features.profile
ignore_imports =
    pkg.features.cart.view -> pkg.features.search

[importlinter:contract:features-direct]
name = Every feature, direct imports only
type = independence
modules =
    pkg.features.*
allow_indirect_imports = True
